//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeJelly.ReportGenerateTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeJelly.ReportGenerateTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time: ###,,,
        ///Netcontrollers: ,,,
        ///,,,
        ///,,,
        ///Silo,Cable,Sensor,Status
        ///36,1,7-Jun,Sensors alarms deactivated
        ///36,2,7-Jun,Sensors alarms deactivated
        ///36,3,7-Jun,Sensors alarms deactivated
        ///36,4,7-Jun,Sensors alarms deactivated
        ///36,5,7-Jun,Sensors alarms deactivated
        ///36,6,7-Jun,Sensors alarms deactivated
        ///35,7,7-Jun,Sensors alarms deactivated
        ///35,8,7-Jun,Sensors alarms deactivated
        ///35,9,7-Jun,Sensors alarms deactivated
        ///35,10,7-Jun,Sensors alarms deactivated
        ///35,11,7-Jun,Sensors alarms deactivated
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Agrolog_example {
            get {
                return ResourceManager.GetString("Agrolog_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         ///СИТ ГРЕЙНБАР        ///Измерение от ###  Температура предупрежденя 30.0
        ///  № |ш.м.п.|Сил.      |       Т1       Т2       Т3       Т4       Т5       Т6
        ///------------------------------------------------------------------------------
        ///  1 | 1 1 2|5-2       |      9.2     20.2      20.4     20.4     19.9     20.1
        ///  2 | 1 1 3|5-84-1    |     13.6     16.6      14.6     13.9     15.8     21.0
        ///  3 | 1 1 4|5-1*      |     21.6     20.7      20.6     20.7     20.1     19.6
        ///  4 | 1 2 1|5-2*      |     13.6     21.8      21 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Grainbar_example {
            get {
                return ResourceManager.GetString("Grainbar_example", resourceCulture);
            }
        }
    }
}
