//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeJelly.tempa.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeJelly.tempa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time: 2001-01-01 00:00:00,,,
        ///Netcontrollers: ,,,
        ///,,,
        ///Silo,Cable,Sensor,Value (°C)
        ///36,1,1,
        ///36,1,2,
        ///36,1,3,
        ///36,1,4,
        ///36,1,5,
        ///36,1,6,
        ///36,1,7,
        ///36,2,1,
        ///36,2,2,
        ///36,2,3,
        ///36,2,4,
        ///36,2,5,
        ///36,2,6,
        ///36,2,7,
        ///36,3,1,
        ///36,3,2,
        ///36,3,3,
        ///36,3,4,
        ///36,3,5,
        ///36,3,6,
        ///36,3,7,
        ///36,4,1,
        ///36,4,2,
        ///36,4,3,
        ///36,4,4,
        ///36,4,5,
        ///36,4,6,
        ///36,4,7,
        ///36,5,1,
        ///36,5,2,
        ///36,5,3,
        ///36,5,4,
        ///36,5,5,
        ///36,5,6,
        ///36,5,7,
        ///36,6,1,
        ///36,6,2,
        ///36,6,3,
        ///36,6,4,
        ///36,6,5,
        ///36,6,6,
        ///36,6,7,
        ///35,7,1,
        ///35,7,2,
        ///35,7,3,
        ///35,7,4,
        ///35, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AgrologPatternReport {
            get {
                return ResourceManager.GetString("AgrologPatternReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///СИТ ГРЕЙНБАР
        ///
        ///Измерение от 01.01.01, 00:00:00  Температура предупрежденя 30.0
        ///  № |ш.м.п.|Сил.      |       Т1       Т2       Т3       Т4       Т5       Т6
        ///------------------------------------------------------------------------------
        ///  1 | 1 1 2|5-2       |      0.0      0.0       0.0      0.0      0.0      0.0
        ///  2 | 1 1 3|5-84-1    |      0.0      0.0       0.0      0.0      0.0      0.0
        ///  3 | 1 1 4|5-1*      |      0.0      0.0       0.0      0.0      0.0      0.0
        ///  4 | 1 2 1|5-2*      |      0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GrainbarPatternReport {
            get {
                return ResourceManager.GetString("GrainbarPatternReport", resourceCulture);
            }
        }
    }
}
